---
title: "STAT 6341"
---

## Numerical Linear Algebra and Statistical Computing

**Term:** Fall 2024, Fall 2025, Fall 2026  
**Instructor:** Yun Wei

## Course description

This graduate course covers numerical linear algebra and statistical computing, including matrix decomposition, optimization, and machine learning.

## Lecture notes

The lecture notes evolve during the semester. <span style="color: red;">It only contains material from the lectures that has no slides provided.</span>

[Download lecture notes (PDF)](files/stat_6341_fall_2026/Stat_6341_lecture_notes.pdf)


## Schedule (Fall 2026)

| Date | Topic |
|---|---|
| August 24 | Multi-Armed Bandit and epsilon greedy algorithm, [Foster and Rakhlin](https://arxiv.org/abs/2312.16730) Section 2.1-2.2 [Scribed lecture notes](files/stat_6341_fall_2026/lectures/lec01.pdf)  |
| August 26 | epsilon greedy and UCB algorithms, [Foster and Rakhlin](https://arxiv.org/abs/2312.16730) Section 2.2-2.3 [Scribed lecture notes](files/stat_6341_fall_2026/lectures/lec02.pdf) |
| August 31 | UCB algorithm, [Foster and Rakhlin](https://arxiv.org/abs/2312.16730) Section 2.2-2.3; Convex functions, Boyd and Vandenberghe Sec 3.1 [Scribed lecture notes](files/stat_6341_fall_2026/lectures/lec03.pdf) |
| September 2 | Convex functions, Boyd and Vandenberghe Sec 3.1; Bisection and Newton's method; strong convexity, Boyd and Vandenberghe Sec 9.1.2 |
| September 9 | Strong convexity, Boyd and Vandenberghe Sec 9.1.2 |
| September 14 | Ridge Regression |
| September 16 | Ridge Regression: GD, SGD |
| September 21 | SGD; and robust regression: MM algorithms; constrained optimization (Boyd and Vandenberghe Sec 5.1-5.2) |
| September 23 | constrained optimization and KKT condition (Boyd and Vandenberghe Sec 5.1, 5.2, 5.5) |
| September 28 |  equality constrained minimization problems (Boyd and Vandenberghe Sec 10.1)  [Scribed lecture notes](files/stat_6341_fall_2026/lectures/lec04.pdf) |
| September 30 |   equality constrained minimization problems (Boyd and Vandenberghe Sec 10.1) and Newton's method (sec 9.5) |
| October 5 |   Newton's method (Boyd and Vandenberghe sec 9.5) and Newton's method with equality constraint ( Sec 10.2) |
| October 7 |   PCA (Guest lecture) |
